### ISSUE TITLE
Install de base - ModuleNotFoundError: No module named 'rules'

### ISSUE THREAD

**Issue by marcu** [be-lb/sdi#1]
Hello @pierremarc 

J'ai pris le code de github. Puis fait un ´pip install -r requirements.txt´

Quand j'essaie d'exécuter la commande ´python manage.py´, l'erreur ´ModuleNotFoundError: No module named 'rules'´

Que faire ?

**Comment by pierremarc** [comment]
requirements.tx est maintenant a jour
