### ISSUE TITLE
Ce bon vieux Rules

### ISSUE THREAD

**Issue by marcu** [be-lb/sdi#3]
Après ces petites modifs manage.py marche et accès à une db.

A chaque commande lancé, le message `ModuleNotFoundError: No module named 'rules'

```
ModuleNotFoundError: No module named 'rules'
```

**Comment by pierremarc** [comment]
requirements.txt a jour maintenant, ca devrait aider.
Et ne pas oublier d'ajuster les settings, voir https://github.com/be-lb/sdi/blob/master/permissions.md#settings
